#!/bin/sh

GROUP_SYSTEM=system
GROUP_SESSION=session

mkdir -p /tmp/amazonPrime/
chgrp $GROUP_SESSION /tmp/amazonPrime/
chmod g+rw /tmp/amazonPrime/

chgrp $GROUP_SYSTEM /data
chmod g+rw /data

mkdir -p /data/amazonPrime/
chgrp $GROUP_SESSION /data/amazonPrime/
chmod g+rw /data/amazonPrime/

if [ -d /data/persistent ];then
  chgrp $GROUP_SYSTEM /data/persistent
  chmod g+rw /data/persistent
fi

if [ -c /dev/nand_env ];then
  chgrp disk /dev/nand_env
  chmod g+rw /dev/nand_env
fi

chgrp $GROUP_SYSTEM /run
chmod g+rw /run

chgrp -R $GROUP_SESSION /run/wpa_supplicant/
chmod -R g+rw /run/wpa_supplicant/

chgrp $GROUP_SESSION /dev/shm/AudioServiceShmem
chmod g+rw /dev/shm/AudioServiceShmem
chgrp $GROUP_SESSION /run/audio_socket
chmod g+rw /run/audio_socket

chgrp -R $GROUP_SYSTEM /dev/v4l/
chmod -R g+rw /dev/v4l/

chgrp -R $GROUP_SYSTEM /sys/module/drm/parameters/
chmod -R g+rw /sys/module/drm/parameters/
chgrp -R $GROUP_SYSTEM /sys/module/aml_drm/parameters/
chmod -R g+rw /sys/module/aml_drm/parameters/

