FILESEXTRAPATHS:prepend := "${THISDIR}/gst1-plugins-good:"

SRC_URI += "file://0001-fix-gst-not-respect-buffer-config.patch"
SRC_URI += "file://0004-support-event-and-dma.patch"
SRC_URI += "file://0005-add-sinput-for-vdin.patch"
SRC_URI += "file://0006-add-more-condition-to-select-stream-in-qtdemux.patch"
SRC_URI += "file://0008-add-audio-dtse-case-in-qtdemux.patch"
SRC_URI += "file://0010-modfiy-free-sequence-to-resolve-video-switch-problam.patch"
SRC_URI += "file://00011-correct-pts-if-have-elst-in-qtdemux.patch"
SRC_URI += "file://00012-add-v4l2av1dec-element.patch"
SRC_URI += "file://00013-add-v4l2mpeg2dec-element.patch"
SRC_URI += "file://00014-add-v4l2-aml-vdec-h.patch"
SRC_URI += "file://00015-add-func-to-set-vdec-parm-in-v4l2dec.patch"
SRC_URI += "file://00017-add-flow-in-vbp-to-adapt-to-the-buf-circulation-of-decoder.patch"
SRC_URI += "file://00018-set-default-capture-vbp-buf-mode.patch"
SRC_URI += "file://00020-add-systemstream-in-v4l2-sinkpad-caps-when-reg.patch"
SRC_URI += "file://00021-SWPL-73078-DTS-wav.patch"
SRC_URI += "file://00022-mode-gst-env-name.patch"
SRC_URI += "file://00023_SH-9750-Dump_decode_frame.patch"
SRC_URI += "file://00024-qtdemux-remove-support-dolby-vision-unknown-Compatibility-ID.patch"
SRC_URI += "file://00026-correct-io-pointer-when-parse-trun.patch"
SRC_URI += "file://00028-fix_SWPL-90736_check_dv_blel_for_mp4.patch"
SRC_URI += "file://00029-qtdemux-remove-cslg-handling.patch"
SRC_URI += "file://00029-v4l2src-patch-for-support-mediactrlsrc.patch"
SRC_URI += "file://00032-set-systemstream-to-false-when-mpeg1.patch"
SRC_URI += "file://00034-SWPL-121124_av1_codecdata_mkvdemux.patch"
SRC_URI += "file://00036-SWPL-101568-support-hls-discontinuity.patch"
SRC_URI += "file://00037-modify-qtdemux-to-parse-sampleAES.patch"
SRC_URI += "file://00038-SWPL-136361-add-qtdemux-set-multiqueue-size.patch"
SRC_URI += "file://00039-fix-cbc1-audio-decrypt.patch"
SRC_URI += "file://00040-fix-webm-drm-support.patch"
SRC_URI += "file://00041-SWPL-149025-refine-mp4-dv-parameter.patch"

PACKAGECONFIG[v4l2] = "-Dv4l2=enabled -Dv4l2-probe=false"
