FILESEXTRAPATHS_prepend := "${THISDIR}/gst1:"
SRC_URI_append = "file://0001-gstreamer-add-poll-api.patch "
SRC_URI_append = "file://0002-modfiy-free-sequence-to-resolve-video-switch-problam.patch "
SRC_URI_append = "file://0003-gstreamer-clcok-adjust-issue.patch "
SRC_URI_append = "file://0004-do-not-post-buffering-in-multiqueue.patch "
