#!/bin/sh

export CAS_TYPE=nagra
export NAGRA_CAS_EMI=0x4020
export LOW_MEM_PLATFORM=1
export DTVKIT_EXT=/usr/lib/libdtvkit_ota_monitor.so
export IRDETO_REGIONAL_FILTER_ENABLE=1

# Starts dtvkit service.
start() {
	printf "Starting dtvkit service: \n"
	/usr/bin/dtvkitserver &
}

stop() {
	printf "Stopping dtvkit service: \n"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

