#!/bin/sh
export iptv_streamtype=0
export LOW_MEM_PLATFORM=1
export TSPLAYER_SUBTILTEFLAG=2
export CAS_TYPE=nagra
export NAGRA_CAS_EMI=0x4020
export DTVKIT_EXT=/usr/lib/libdtvkit_ota_monitor.so
export IRDETO_REGIONAL_FILTER_ENABLE=1

# Starts arka service.
start() {
	printf "Starting arka service: \n"

	/usr/bin/Arka &
}

stop() {
	printf "Stopping arka service: \n"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?

