#!/bin/sh
#sysctl -w kernel.hotplug=/sbin/mdev
mdev -s

#
# We might have mounted something over /dev, see if /dev/initctl is there.
#
if test ! -p /dev/initctl
then
        rm -f /dev/initctl
        mknod -m 600 /dev/initctl p
fi

