#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Copied from initramfs-framework. The core of this script probably should be
# turned into initramfs-framework modules to reduce duplication.
udev_daemon() {
    OPTIONS="/sbin/udev/udevd /sbin/udevd /lib/udev/udevd /lib/systemd/systemd-udevd"

    for o in $OPTIONS; do
        if [ -x "$o" ]; then
            echo $o
            return 0
        fi
    done

    return 1
}

_UDEV_DAEMON=`udev_daemon`

early_setup() {
    mkdir -p /proc
    mkdir -p /sys
    mount -t proc proc /proc
    mount -t sysfs sysfs /sys
    mount -t devtmpfs none /dev
    mount -t tmpfs tmpfs /tmp

    mkdir -p /run
    mkdir -p /var/run

    mkdir -p /mnt

    $_UDEV_DAEMON --daemon
    udevadm trigger --action=add
}

boot_root() {
    # Watches the udev event queue, and exits if all current events are handled
    udevadm settle

    exec /sbin/init
}

early_setup
boot_root
