#For WesterOS
DISTRO_FEATURES_remove = " mesa mesa-gl x11"
#DISTRO_FEATURES_append = " opencdm"
DISTRO_FEATURES_append = " westeros enable_icrypto_openssl rdkshell safec one-rdk no-rdk-deps aml-thunder"
DISTRO_FEATURES_append = " tts"
DISTRO_FEATURES_append = " aml-launcher"
DISTRO_FEATURES_append = " aml-thunder"
DISTRO_FEATURES_append = " youtube"
DISTRO_FEATURES_append = " amazon"
DISTRO_FEATURES_append = " mediaplayer"
DISTRO_FEATURES_append = " netflix6"

PREFERRED_VERSION_amazon-prime-video = "4.0"
PREFERRED_VERSION_wpa-supplicant = "2.10"

