#For Valhall G57
PREFERRED_PROVIDER_virtual/egl = "libgles-eabihf-valhall-wayland-drm"
PREFERRED_PROVIDER_virtual/egl-native = "libgles-eabihf-valhall-wayland-drm"
PREFERRED_PROVIDER_virtual/libgbm = "libgles-eabihf-valhall-wayland-drm"
PREFERRED_PROVIDER_virtual/libgles1 = "libgles-eabihf-valhall-wayland-drm"
PREFERRED_PROVIDER_virtual/libgles2 = "libgles-eabihf-valhall-wayland-drm"
PREFERRED_PROVIDER_virtual/libgl = "libgles-eabihf-valhall-wayland-drm"
PREFERRED_PROVIDER_virtual/libgl-native = "libgles-eabihf-valhall-wayland-drm"
PREFERRED_PROVIDER_virtual/mesa-gl = "libgles-eabihf-valhall-wayland-drm"
PREFERRED_PROVIDER_virtual/mesa = "libgles-eabihf-valhall-wayland-drm"
PREFERRED_PROVIDER_virtual/nativesdk-egl = "libgles-eabihf-valhall-wayland-drm"
PREFERRED_PROVIDER_virtual/nativesdk-libgl = "libgles-eabihf-valhall-wayland-drm"

