#For WesterOS
DISTRO_FEATURES:remove = " mesa mesa-gl x11"
#DISTRO_FEATURES:append = " opencdm"
DISTRO_FEATURES:append = " westeros enable_icrypto_openssl rdkshell safec one-rdk no-rdk-deps aml-thunder"
DISTRO_FEATURES:append = " tts"
DISTRO_FEATURES:append = " aml-launcher"
DISTRO_FEATURES:append = " aml-thunder"
DISTRO_FEATURES:append = " youtube"
DISTRO_FEATURES:append = " amazon"
DISTRO_FEATURES:append = " mediaplayer"
DISTRO_FEATURES:append = " netflix"
DISTRO_FEATURES:append = " disney"
DISTRO_FEATURES:append = " arka use-egl arka-project-aml"

PREFERRED_VERSION_amazon-prime-video = "5.0"
PREFERRED_VERSION_netflix = "dpi7.0"
PREFERRED_VERSION_wpa-supplicant = "2.10"

